### ISSUE TITLE
Peer-to-peer-code-reviews

### ISSUE THREAD

**Issue by fmshot2** [Ndaboom/portofolio#5]
Hi Ndaboom, you have done a great job!

Here are some issues noticed in your code:

1.  Please add button hover effects on the buttons of your code.
2. You could also please reduce the spacing between each card title and the icon at the top of the card. This is to bring it in line with the figma design.

Welldone so far!!

**Comment by Ndaboom** [comment]
I will, Thanks for the review @fmshot2
